week6/day4/chirpy/config/routes.rb
Rails.application.routes.draw do

  root 'chirps#index'

  resources :chirps
  resources :users

  get "/login" => 'sessions#new', as: :login
  post "/login" => 'sessions#create'
  delete "/logout" => 'sessions#destroy', as: :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

week6/day4/chirpy/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

week6/day4/chirpy/app/models/chirp.rb
class Chirp < ApplicationRecord
  belongs_to :user

  delegate :avatar, to: :user

  default_scope { order(created_at: :desc) }

  # def avatar
  #   user.avatar
  # end

  def is_owner?(this_user)
    user == this_user
  end


end

week6/day4/chirpy/app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

week6/day4/chirpy/app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

week6/day4/chirpy/app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

week6/day4/chirpy/app/models/user.rb
class User < ApplicationRecord
  has_many :chirps
  has_secure_password

  acts_as_follower
  acts_as_followable

  # default_scope { where(active: true) }

  # User.active
  # scope :active, -> { where(active: true) }

  validates :username, :avatar, presence: true
  validates :username, uniqueness: true
  # validates_uniqueness_of :username

  # def avatar
  #   attributes["avatar"].blank? ? "https://robohash.org/#{username}.png" : attributes["avatar"]
  # end

  def to_s
    username
  end

end

week6/day4/chirpy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :load_popular_users

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    unless current_user
      flash[:warning] = "You need to be logged in to do this."
      redirect_to login_path
    end
  end


  def load_popular_users
    if params[:controller] == "users" && params[:action] == "show"
      starter = User.where("id != ?", params[:id])
    else
      starter = User.all
    end
    @popular_users ||= starter.order(followers_count: :desc).limit(4)
  end

end

week6/day4/chirpy/app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController

  before_action :require_user, only: [:new, :create, :destroy]
  before_action :is_owner, only: [:destroy]

  def index
    @chirps = Chirp.page(params[:page])
  end

  def show
    @chirp = Chirp.find(params[:id])
  end

  def new
    @chirp = Chirp.new
  end

  def create
    @chirp = current_user.chirps.new(chirp_params)
    if @chirp.save
      redirect_to :root
    else
      render :new
    end
  end

  def destroy
    @chirp.destroy
    redirect_to :root
  end

  private

  def chirp_params
    # {chirp: {user_id: , body:}}
    params.require(:chirp).permit(:body)
  end

  def is_owner
    @chirp = current_user.chirps.find_by(id: params[:id])
    unless @chirp && @chirp.user == current_user
      flash[:danger] = "That's not your chirp, bucky"
      redirect_to :root
    end
  end

end

week6/day4/chirpy/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.username}!"
      redirect_to :root
    else
      flash[:danger] = "Incorrect credentials. Please try again."
      redirect_to :login
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end

end

week6/day4/chirpy/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:edit, :show, :update]

  before_action :require_user, only: [:edit, :update]

  before_action :require_self, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # send them an email
      UserMailer.signup(@user).deliver
      session[:user_id] = @user.id
      redirect_to @user
      # redirect_to "/users/#{@user.id}"
      # redirect_to controller: "users", action: "show", id: @user.id

      # url_for(@user)
      #   - Check class name (User)
      #   - "#{class_name}_path(id: thing.id)"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :bio, :avatar, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def require_self
    unless @user == current_user
      flash[:danger] = "Keep your hands to yourself, ya creep."
      redirect_to :root
    end
  end

end

week6/day4/chirpy/app/helpers/application_helper.rb
module ApplicationHelper
end

week6/day4/chirpy/app/helpers/chirps_helper.rb
module ChirpsHelper
end

week6/day4/chirpy/app/helpers/sessions_helper.rb
module SessionsHelper
end

week6/day4/chirpy/app/helpers/users_helper.rb
module UsersHelper
end

week6/day4/chirpy/app/views/chirps/_chirp.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to chirp.user do %>
      <%= image_tag chirp.user.avatar, class: "media-object img-circle" %>
    <% end %>
  </div>
  <div class="media-body">
    <%= simple_format chirp.body %>
    <!-- <small>Chirped by <%= chirp.user.username %> <%= link_to "#{time_ago_in_words(chirp.created_at)} ago", controller: "chirps", action: "show", id: chirp.id %></small> -->
    <!-- <small>Chirped by <%= chirp.user.username %> <%= link_to "#{time_ago_in_words(chirp.created_at)} ago", "/chirps/#{chirp.id}" %></small> -->
    <!-- <small>Chirped by <%= chirp.user.username %> <%= link_to "#{time_ago_in_words(chirp.created_at)} ago", chirp_path(id: chirp.id) %></small> -->
    <!-- <small>Chirped by <%= chirp.user.username %> <%= link_to "#{time_ago_in_words(chirp.created_at)} ago", chirp_path(chirp.id) %></small> -->
    <!-- <small>Chirped by <%= chirp.user.username %> <%= link_to "#{time_ago_in_words(chirp.created_at)} ago", chirp_path(chirp) %></small> -->
    <strong>Chirped by <%= link_to chirp.user.username, chirp.user, class: "btn btn-default" %> <%= link_to "#{time_ago_in_words(chirp.created_at)} ago", chirp %>
      <% if chirp.is_owner? current_user %>
        <%= button_to "EXTERMINATE!!", chirp, method: :delete, class: "btn btn-danger" %>
      <% end %>
    </strong>
  </div>
</div>

week6/day4/chirpy/app/views/chirps/index.html.erb
<div class="row">
  <div class="col-lg-6 col-md-8 col-xs-10">
    <%= paginate @chirps %>

    <% @chirps.each do |chirp| %>
      <% render partial: "chirps/chirp", locals: {chirp: chirp} %>
    <% end %>

    <% @chirps.each do |srhder5t| %>
      <% render srhder5t %>
    <% end %>

    <%= render @chirps %>

    <%= paginate @chirps %>
  </div>
  <div class="col-lg-6 col-md-4 col-xs-2">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>

</div>

week6/day4/chirpy/app/views/chirps/new.html.erb
<h1>Chirp away!</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for @chirp, html: {class: "form-horizontal"} do |f| %>

        <%= f.input :body %>
        <%= f.button :submit %>

      <% end %>
    </div>
  </div>
</div>

week6/day4/chirpy/app/views/chirps/show.html.erb
<% render partial: "chirp", locals: {chirp: @chirp} %>
<%= render @chirp %>

week6/day4/chirpy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chirpy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.svg", class: "img-responsive" %>
      <% end %>
      <!-- <%= link_to "Chirpy", root_path, class: "navbar-brand" %> -->
      <!-- <a class="navbar-brand" href="#">Chirpy</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Users", users_path %></li>
        <li><a href="#">About</a></li>
      </ul>
      <div class="navbar-right">
        <% if current_user %>
          <%= link_to "Chirp!", new_chirp_path, class: "btn btn-success" %>
          <%= link_to "Logout!", logout_path, method: :delete, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "Login!", login_path, class: "btn btn-primary" %>
          <%= link_to "Signup!", new_user_path, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <div class="container">
      <% if flash.any? %>
        <% flash.each do |klass, message| %>
          <div class="alert alert-<%= klass %>" role="alert">
            <p>
              <%= message %>
            </p>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
    <div class="container-fluid">
      <div class="row">
        <% @popular_users.each do |user| %>
          <div class="col-md-3">
            <%= link_to user do %>
              <%= image_tag user.avatar, class: "img-responsive" %>
              <h6><%= user.username %></h6>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

  </body>
</html>

week6/day4/chirpy/app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>

  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.input :avatar %>
  <%= f.input :bio %>
  <%= f.button :submit %>

<% end %>

week6/day4/chirpy/app/views/users/edit.html.erb
<h1>Edit!</h1>

<%= render "form" %>

week6/day4/chirpy/app/views/users/index.html.erb
<!-- <% @users.each_slice(4) do |row| %>
  <div class="row">
    <% row.each do |user| %>
      <div class="col-xs-3">
        <%= image_tag user.avatar, class: "img-responsive" %>
      </div>
    <% end %>
  </div>
<% end %> -->

<% @users.each do |user| %>
  <div class="col-md-3 col-sm-6">
    <%= link_to user, class: "btn btn-default" do %>
      <%= image_tag user.avatar, class: "img-responsive" %>
    <% end %>
  </div>
<% end %>

week6/day4/chirpy/app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= render "form" %>

week6/day4/chirpy/app/views/users/show.html.erb
<div class="row">
  <div class="col-md-9">
    <!-- Main -->
    <div class="row">
      <div class="col-md-3">
        <%= image_tag @user.avatar, class: "img-responsive" %>
        <% if current_user == @user %>
          <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="col-md-9">
        <h2><%= @user.username %></h2>
        <%= simple_format @user.bio %>
        <h3>Chirps</h3>
        <%= render @user.chirps %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <!-- Sidebar -->
    <h4>Following</h4>
    <ul class="list-unstyled">
      <% if @user.followees(User).count > 0 %>
        <% @user.followees(User).each do |user| %>
          <li><%= link_to user.username, user %></li>
        <% end %>
      <% else %>
        <p>
          They ain't following no body
        </p>
      <% end %>
    </ul>
    <h4>Followers</h4>
    <ul class="list-unstyled">
      <% @user.followers(User).each do |user| %>
        <li><%= link_to user.username, user %></li>
      <% end %>
    </ul>
  </div>
</div>